[package]
name = "rs-ray-tracer"
version = "0.1.0"
authors = ["Maxime Poncet <maxime.poncet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
itertools = "0.10.0"
